### ISSUE TITLE
Aghios Dimitrios Study Case: Add as owner

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#144]
In order to be able to take the screentshots of the forms (in edit mode) for deliverable D1.4 I need my user in CSIS added as study case owner.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by maesbri** [comment]
I cannot see the "edit" button for each of the steps in order to open the corresponding forms. Maybe is it because of being "team member" instead of "owner"? (for the naples DC that was the case and I was able to open the forms in "edit" mode)

![image](https://user-images.githubusercontent.com/9677881/74528070-94faba80-4f27-11ea-99aa-e1b9cfa894bf.png)

**Comment by patrickkaleta** [comment]
> I cannot see the "edit" button for each of the steps in order to open the corresponding forms. Maybe is it because of being "team member" instead of "owner"? (for the naples DC that was the case and I was able to open the forms in "edit" mode)

Yes, it's not visible for you, because you're "just" a team member and not the owner. I made you an owner now, so you should be able to see the button now.

**Comment by maesbri** [comment]
thanks ... although either I am doing something wrong or there is a bug, but even being owner I cannot see the edit feature in the forms.
I logged out and in again just in case, but still the same issue.

**Comment by patrickkaleta** [comment]
> thanks ... although either I am doing something wrong or there is a bug, but even being owner I cannot see the edit feature in the forms.
> I logged out and in again just in case, but still the same issue.

okay, now I found the real problem. The user **miguel.esbri** was added to this study, but I'm guessing you're using **miguel.esbri@ atos.net**.

I switched the two users in that study. Please try again now :)

**Comment by maesbri** [comment]
thanks, now it works :)
